### ISSUE TITLE
Generate 3D structure from SMILES?

### ISSUE THREAD

**Issue by dizhou-wu** [ADicksonLab/AGDIFF#6]
Hi, this is amazing work! I just have a question: Can this model generate a molecule's structure from an input SMILES? If so, is there any example code for how to do this?

**Comment by andrewyzy** [comment]
Thank you for your interest and kind words! Yes, the model can indeed generate molecular structures from SMILES input. I'll provide a code example soon demonstrating how to accomplish this using the model.
Stay tuned!

**Comment by dizhou-wu** [comment]
Thanks! Looking forward to the example.

**Comment by andrewyzy** [comment]
Hey @dizhou-wu! I've just committed a new file smiles_generation.py to the repository that demonstrates how to generate 3D structures from SMILES input.

You can generate a conformer by running:
python smiles_generation.py model.pt --smiles 'CC(C)(C(=O)NC(C))' --out_sdf output_conformer.sdf

This is a basic example, but it should give you a good foundation to build upon for other use cases. Keep in mind that you might need to adjust some parameters/code depending on your specific needs.

**Comment by LucianoPenaTejo** [comment]
Hi, I am interested in using this module, but I can't escape the following error:

`ModuleNotFoundError: No module named 'utils.datasets'`.
